all:
  hosts:
    docker-host-1:
      ansible_host: 192.168.1.101
      ansible_user: your-username
    docker-host-2:
      ansible_host: 192.168.1.102
      ansible_user: your-username

  children:
    docker_hosts:
      hosts:
        docker-host-1:
        docker-host-2:
      vars:
        ansible_python_interpreter: /usr/bin/python3
