---
# CIS Docker Benchmark 1.1 Checks

- name: Start check for profile level {{ profile_level }}
  debug:
    msg: "Applying CIS Benchmark {{ profile_level }}"

# 1.1.1 Ensure a separate partition for containers
- name: Check if /var/lib/docker is a separate partition
  command: grep '/var/lib/docker\s' /proc/mounts
  register: docker_partition_check
  changed_when: false
  failed_when: docker_partition_check.rc != 0
  tags:
    - 1.1.1

# 1.1.2 Ensure only trusted users are allowed to control Docker daemon
- name: Check Docker group membership
  command: getent group docker
  register: docker_group_members
  changed_when: false
  tags:
    - 1.1.2

- name: Fail if untrusted users are part of the Docker group
  fail:
    msg: "Untrusted users found in Docker group. Check group membership."
  when: "'<untrusted_user>' in docker_group_members.stdout"
  tags:
    - 1.1.2

# 1.1.3 to 1.1.18 Ensure auditing is configured for Docker files and directories
- name: Define audit paths
  set_fact:
    docker_audit_paths:
      - path: /usr/bin/dockerd
      - path: /run/containerd
      - path: /var/lib/docker
      - path: /etc/docker
      - path: /usr/bin/containerd
      - path: /usr/bin/containerd-shim
      - path: /usr/bin/containerd-shim-runc-v1
      - path: /usr/bin/containerd-shim-runc-v2
      - path: /usr/bin/runc
      - path: /etc/containerd/config.toml
      - path: /etc/default/docker
      - path: /etc/docker/daemon.json
      - path: /etc/sysconfig/docker
  tags:
    - 1.1.3
    - 1.1.4
    - 1.1.5
    - 1.1.6
    - 1.1.7
    - 1.1.8
    - 1.1.9
    - 1.1.10
    - 1.1.11
    - 1.1.12
    - 1.1.13
    - 1.1.14
    - 1.1.15
    - 1.1.16
    - 1.1.17
    - 1.1.18

- name: Check audit rules for Docker files and directories
  shell: "auditctl -l | grep {{ item.path }}"
  with_items: "{{ docker_audit_paths }}"
  register: audit_rule_checks
  changed_when: false
  tags:
    - 1.1.3
    - 1.1.4
    - 1.1.5
    - 1.1.6
    - 1.1.7
    - 1.1.8
    - 1.1.9
    - 1.1.10
    - 1.1.11
    - 1.1.12
    - 1.1.13
    - 1.1.14
    - 1.1.15
    - 1.1.16
    - 1.1.17
    - 1.1.18

- name: Report missing audit rules for Docker files and directories
  debug:
    msg: "Audit rule for {{ item.item.path }} is missing"
  with_items: "{{ audit_rule_checks.results }}"
  when: item.stdout == ""
  tags:
    - 1.1.3
    - 1.1.4
    - 1.1.5
    - 1.1.6
    - 1.1.7
    - 1.1.8
    - 1.1.9
    - 1.1.10
    - 1.1.11
    - 1.1.12
    - 1.1.13
    - 1.1.14
    - 1.1.15
    - 1.1.16
    - 1.1.17
    - 1.1.18
