---
# CIS Docker Benchmark 1.1 Remediation Tasks

- name: Start remediation for profile level {{ profile_level }}
  debug:
    msg: "Applying CIS Benchmark {{ profile_level }}"

# 1.1.1 Ensure a separate partition for containers
- name: Remediate Create a separate partition for /var/lib/docker (manual step required)
  debug:
    msg: "Creating a separate partition for /var/lib/docker is a manual process. Please ensure this is implemented."
  tags:
    - 1.1.1

# 1.1.2 Ensure only trusted users are allowed to control Docker daemon
- name: Remove untrusted users from the Docker group
  shell: "gpasswd -d {{ item }} docker"
  with_items:
    - <untrusted_user> # Replace with specific usernames
  ignore_errors: true
  tags:
    - 1.1.2

# 1.1.3 to 1.1.18 Ensure auditing is configured for Docker files and directories
- name: Add audit rules for Docker directories
  lineinfile:
    path: "{{ audit_rules_file }}"
    line: "-w {{ item.path }} -p {{ item.perm }} -k docker"
    state: present
  with_items: "{{ docker_directories }}"
  tags:
    - 1.1.3
    - 1.1.4
    - 1.1.5
    - 1.1.6
    - 1.1.7
    - 1.1.8
    - 1.1.9
    - 1.1.10
    - 1.1.11
    - 1.1.12
    - 1.1.13
    - 1.1.14
    - 1.1.15
    - 1.1.16
    - 1.1.17
    - 1.1.18

- name: Add audit rules for Docker files
  lineinfile:
    path: "{{ audit_rules_file }}"
    line: "-w {{ item.path }} -k docker"
    state: present
  with_items: "{{ docker_files }}"
  tags:
    - 1.1.3
    - 1.1.4
    - 1.1.5
    - 1.1.6
    - 1.1.7
    - 1.1.8
    - 1.1.9
    - 1.1.10
    - 1.1.11
    - 1.1.12
    - 1.1.13
    - 1.1.14
    - 1.1.15
    - 1.1.16
    - 1.1.17
    - 1.1.18

- name: Restart the audit daemon
  service:
    name: auditd
    state: restarted
  tags:
    - 1.1.3
    - 1.1.4
    - 1.1.5
    - 1.1.6
    - 1.1.7
    - 1.1.8
    - 1.1.9
    - 1.1.10
    - 1.1.11
    - 1.1.12
    - 1.1.13
    - 1.1.14
    - 1.1.15
    - 1.1.16
    - 1.1.17
    - 1.1.18
